config/routes.rb
Einbeiniger::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :proposals do
    collection do
      get 'admin', action: :admin, as: 'admin'
      post 'disable', action: :disable_proposals, as: 'disable'
      post 'enable', action: :enable_proposals, as: 'enable'
    end
    member do
      post 'update_state/:p_action', action: :update_state, as: 'update_state'
    end
  end

  get "static_page/home"
  get "user" => redirect("/users/edit")

  devise_for :users

  root :to => "static_page#home"
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  include AASM

  has_paper_trail

  belongs_to :user
  belongs_to :show

  validates :user_id,
    presence: true

  validates :title,
    presence: true,
    length: {in: 4..80}

  validates :description,
    presence: true,
    length: {in: 4..1024}

  def translated_state
    I18n.t("proposal.#{self.state}")
  end

  aasm column: 'state' do
    state :created, initial: true
    state :accepted
    state :rejected
    state :called
    state :backup

    event :accept do
      transitions from: [:created,:rejected,:backup], to: :accepted
    end

    event :reject do
      transitions from: [:created,:accepted,:backup], to: :rejected
    end

    event :backup do
      transitions from: [:created,:accepted,:rejected], to: :backup
    end

    event :call do
      transitions from: [:accepted, :backup], to: :called
    end

  end

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  def self.proposals_enabled?
    proposals_enabled = Setting.where(key: "proposals_enabled").first
    proposals_enabled && proposals_enabled.value == "true"
  end
end

app/models/show.rb
class Show < ActiveRecord::Base
  has_many :proposals
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :proposals
  has_paper_trail
  validates :name, presence: true
  validates :year_of_birth, presence: true

  def moderator?
    self.role == "moderator"
  end

  def age
    current_year = DateTime.now.year
    current_year - year_of_birth
  end

  # bypass re-entering current password for edit
  def update_with_password(params={})
    params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    update_attributes(params)

    clean_up_passwords
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  # Devise override for profile updates
  def configure_permitted_parameters
    user_params = %i(phone year_of_birth location name skype)
    devise_parameter_sanitizer.for(:account_update) << user_params
    devise_parameter_sanitizer.for(:sign_up) << user_params
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_proposal, only: [:show, :edit, :update, :destroy, :update_state]
  # GET /proposals
  # GET /proposals.json
  def index
    if current_user.moderator?
      @proposals = Proposal.all
    else
      @proposals = Proposal.where(:user_id => current_user.id)
    end
  end

  def admin
    throw "No way man" unless current_user.moderator?
    @proposals = Proposal.all
    @proposals_enabled = Setting.where(key: "proposals_enabled").first.try(:value) || false
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
  end

  # GET /proposals/new
  def new
    @proposal = Proposal.new
  end

  # GET /proposals/1/edit
  def edit
  end

  def update_state
    throw "No way man" unless current_user.moderator?
    action = params[:p_action]
    if @proposal.send("may_#{action}?")
      @proposal.send("#{action}!")
      redirect_to @proposal, notice: t('proposal.state_changed')
    else
      redirect_to @proposal, alert: t('proposal.state_not_changed')
    end
  end

  # POST /proposals
  # POST /proposals.json
  def create
    throw "Go away, you are drunk" unless Setting.proposals_enabled?
    @proposal = Proposal.new(proposal_params)
    @proposal.user = current_user
    respond_to do |format|
      if @proposal.save
        format.html { redirect_to @proposal, notice: 'Proposal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @proposal }
      else
        format.html { render action: 'new' }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proposals/1
  # PATCH/PUT /proposals/1.json
  def update
    respond_to do |format|
      if @proposal.update(proposal_params)
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html { redirect_to proposals_url }
      format.json { head :no_content }
    end
  end

  def enable_proposals
    throw "No way man" unless current_user.moderator?
    s = Setting.where(key: "proposals_enabled").first_or_create
    s.value = "true"
    s.save
    redirect_to admin_proposals_path
  end

  def disable_proposals
    throw "No way man" unless current_user.moderator?
    s = Setting.where(key: "proposals_enabled").first
    s.value = "false"
    s.save
    redirect_to admin_proposals_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proposal
      @proposal = Proposal.find(params[:id])
      redirect_to new_user_session_url unless (@proposal.user == current_user or current_user.moderator?)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proposal_params
      params[:proposal].permit(:title, :description)
    end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
    #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Einbeiniger</title>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
<script type="text/javascript">
/* <![CDATA[ */
(function() {
    var s = document.createElement('script');
    var t = document.getElementsByTagName('script')[0];

    s.type = 'text/javascript';
    s.async = true;
    s.src = '//api.flattr.com/js/0.6/load.js?mode=auto';

    t.parentNode.insertBefore(s, t);
 })();
/* ]]> */
</script>
</head>
<body>
<div id="wrap">
  <%= render "shared/menu" %>
  <div class="container main-container">
    <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
  <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% end %>
    <%= yield %>
  </div>
</div>
<div id="footer">
  <div class="container">
    <p class="text-muted credit">
      &copy; 2013-<%= Time.now.year %>,
      <a href="https://twitter.com/timbuchwaldt">@timbuchwaldt</a>,
      <a href="https://twitter.com/kgzme">@kgzme</a>
      <span style="float:right;display:inline-block">
        <a class="FlattrButton" href="http://einbeiniger.herokuapp.com/" title="Einbeinigen unterstützen" lang="de_DE" rel="flattr;uid:21studios;category:software;button:compact">Entwicklung des Einbeinigen unterstützen</a>
      </span>
    </p>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.slim
doctype html
html lang="de"
  head
    meta charset="utf-8" /
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title="#{yield(:title) if content_for?(:title)} Einbeiniger"
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags

  body
    = render partial: 'shared/menu'
    .row
      .large-12
        = yield

    footer.row
      .large-12.columns
        hr
        .row
          .large-6.columns
            p &copy; 2013-2014
          .large-6.columns
            ul.inline-list.right
              li=link_to "Tim Buchwaldt", "https://alpha.app.net/timbuchwaldt"
              li=link_to "Klaus Zanders", "https://alpha.app.net/klaustopher"
              li=link_to "Die Entwicklung des Einbeinigen unterstützen", "http://einbeiniger.herokuapp.com", title: "Einbeinigen unterstützen", lang: "de_DE", rel: "flattr;uid:21studios;category:software;button:compact", class: "FlattrButton"

app/views/proposals/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-md-8">
    <%= simple_form_for(@proposal, html: { class: 'form-horizontal' },
    wrapper: :horizontal_form,
    wrapper_mappings: {
      check_boxes: :horizontal_radio_and_checkboxes,
      radio_buttons: :horizontal_radio_and_checkboxes,
      file: :horizontal_file_input,
      boolean: :horizontal_boolean
      }) do |f| %>
      <%= f.input :title %>
      <%= f.input :description, input_html: { rows: 10 } %>
      <%= f.button :submit %>
      <% end %>
    </div>
  </div>

app/views/proposals/_moderator_actions.html.erb
<% %w'accept reject backup call'.each do |action| %>
  <% if @proposal.send("may_#{action}?") %>
    <%= link_to t("proposal.#{action}"), update_state_proposal_path(@proposal,action), method: :post, class: 'btn btn-default btn-sm' %>
  <% end %>
<% end %>
<br />

app/views/proposals/_user_details.html.erb
<h2>Gastdetails</h2>

<dl class="dl-horizontal">
  <dt>Name</dt>
    <dd><%= @proposal.user.name %></dd>
  <dt>Alter</dt>
    <dd><%= @proposal.user.age %></dd>
  <dt>Ort</dt>
    <dd><%= @proposal.user.location %></dd>
  <dt>Telefon</dt>
    <dd><%= @proposal.user.phone %></dd>
  <dt>Email</dt>
    <dd><%= @proposal.user.email %></dd>
  <dt>Skype</dt>
    <dd><%= link_to @proposal.user.skype, "skype:#{@proposal.user.skype}" %></dd>
</dl>

app/views/proposals/admin.html.erb
<% @proposals.group_by(&:state).each do |state, proposals| %>
  <h2><%= t("proposal.#{state}") %></h2>


  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Status</th>
        <th>Gast</th>

        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

  <tbody>
    <% proposals.each do |proposal| %>
      <tr>
        <td><%= link_to proposal.title, proposal %></td>
        <td><%= proposal.translated_state %></td>
        <td><%= proposal.user.name %></td>
        <td><%= proposal.created_at %></td>
        <td><%= link_to 'Details', proposal %></td>
        <td><%= link_to 'Bearbeiten', edit_proposal_path(proposal) %></td>
        <td><%= link_to 'Löschen', proposal, method: :delete, data: { confirm: 'Gaaaanz sicher?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<h3>Einstellungen</h3>
<% if @proposals_enabled == "true" %>
  <%= link_to "Vorschläge deaktivieren", disable_proposals_path, method: "post" %>
<% else %>
  <%= link_to "Vorschläge aktivieren", enable_proposals_path, method: "post" %>
<% end %>

app/views/proposals/edit.html.erb
<h1>Gesprächsvorschlag bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @proposal %> |
<%= link_to 'Zurück', proposals_path %>

app/views/proposals/index.html.erb
<h1>Gesprächsvorschläge</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @proposals.each do |proposal| %>
      <tr>
        <td><%= proposal.title %></td>
        <td><%= proposal.translated_state %></td>
        <td><%= link_to 'Details', proposal %></td>
        <td><%= link_to 'Bearbeiten', edit_proposal_path(proposal) %></td>
        <td><%= link_to 'Löschen', proposal, method: :delete, data: { confirm: 'Gaaaanz sicher?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if Setting.proposals_enabled? %>
  <%= link_to 'Neuen Vorschlag anlegen', new_proposal_path %>
<% else %>
  Aktuell können keine neuen Vorschläge angelegt werden.
<% end %>

app/views/proposals/new.html.erb
<h1>Neuer Vorschlag</h1>

<%= render 'form' %>

<%= link_to 'Zurück', proposals_path %>

app/views/proposals/show.html.erb
<h1>Vorschlag: <%= @proposal.title %></h1>
<p>
  <b>Thema:</b> <%= @proposal.description %>
</p>
<p>
  <b>Status:</b> <%= @proposal.translated_state %> <br />
  <% if @proposal.show %><b>Show:</b> <%= @proposal.show.date %><% end %>
</p>

<%= render 'moderator_actions' if current_user.moderator? %>
<%= render 'user_details' if current_user.moderator? %>


<%= link_to t(:edit), edit_proposal_path(@proposal) %> |
<%= link_to t(:back), proposals_path %>

app/views/proposals/update.html.erb
<h1>Proposals#update</h1>
<p>Find me in app/views/proposals/update.html.erb</p>

app/views/shared/_menu.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "WRINT Einbeiniger", root_path, { class: 'navbar-brand' } %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "Vorschläge", proposals_path %></li>
          <% if current_user.moderator? %>
          <li><%= link_to "Admin", admin_proposals_path %></li>
          <% end %>
        <% end %>

      </ul>

      <% if current_user %>
        <ul class="nav navbar-nav navbar-right navbar-form">
        <li>
        <div class="btn-group">
          <%= link_to raw("<span class=\"fa fa-user\"></span> #{h(current_user.name || current_user.email)}"), edit_user_registration_path, { title: 'Profil bearbeiten', class: 'btn btn-default' } %>
          <%= link_to raw('<span class="fa fa-sign-out"></span>'), destroy_user_session_path, { method: :delete, class: 'btn btn-default', title: 'Abmelden' } %>
        </div>
        </li>
      </ul>
    <% else %>
        <%= form_for(:user, :url => session_path(:user), html: { class: 'navbar-form navbar-right' }) do |f| %>
        <div class="form-group">
        <%= f.email_field :email, placeholder: 'Email', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, placeholder: "Passwort", class: 'form-control' %>
      </div>
      <div class="btn-group">
        <%= f.submit "Login", class: 'btn btn-success' %>
        <%= link_to "Registrieren", new_user_registration_path, { class: 'btn btn-default' } %>
      </div>
    <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/shared/_menu.html.slim
.fixed
  nav.top-bar data={ topbar: "" }
    ul.title-area
      li.name
        h1
          =link_to "WRINT Einbeiniger", root_path
      li.toggle-topbar.menu-icon
        a href="#" Menü

    section.top-bar-section
      ul.left
        li.divider
        - if current_user
          li=link_to "Vorschläge", proposals_path
          li.divider
          -if current_user.moderator?
            li= link_to "Admin", admin_proposals_path
            li.divider
      ul.right
        li.divider
        - if current_user
          li.has-dropdown
            a href="#"
              = h(current_user.name || current_user.email)
            ul.dropdown
              li=link_to "Profil bearbeiten", edit_user_registration_path
              li=link_to "Abmelden", destroy_user_session_path, { method: :delete }
        - else
          li.has-form
            = form_for :user, :url => session_path(:user) do |f|
              .row.collapse
                .large-3.small-3.columns= f.email_field :email, placeholder: 'Email'
                .large-3.small-3.columns= f.password_field :password, placeholder: "Passwort"
                .large-5.small-5.columns
                  .button-bar
                    .button-group.round
                      = f.submit "Login", class: "tiny button"
                      = link_to "Registrieren", new_user_registration_path, class: "tiny button "

app/views/static_page/home.html.erb
<div class="page-header">
  <h1>Willkommen zum Einbeinigen</h1>
</div>
<% if current_user %>
  <div class="lead">
  <p>Hallo,</p>

  <% unless current_user.proposals.empty? %>
    <p>Deine aktuellen Vorschläge:</p>
  <ul>
    <% current_user.proposals.each do |proposal| %>
      <li><%= link_to "#{proposal.title} (#{proposal.translated_state})", proposal_path(proposal) %></li>
  <% end %>
  </ul>
<% else %>
    <p>Keine Vorschläge vorhanden.</p>
<% end %>
<% if Setting.proposals_enabled? %>
<%= link_to raw('<span class="fa fa-pencil"></span> Neuen Vorschlag anlegen'), new_proposal_path, class: 'btn btn-success btn-lg' %>
<% else %>

<a href="#" class="btn btn-default btn-lg "><i class="fa fa-pencil"></i>Aktuell können keine Vorschläge erstellt werden.</a>
<br />
<small>Holgi gibt auf Twitter bekannt, wenn Vorschläge erstellt werden können.</small>
<% end %>
</div>

<% else %>
  <div class="lead">
  <p>Hier kannst du dich für die Hörertalksendung Ferngespräche anmelden.</p>
  <p>Dafür brauchst du einen Account, den du <%= link_to "hier", new_user_registration_path  %> erstellen kannst. Falls du schon einen Account hast, kannst du dich <%= link_to "hier", new_user_session_path %> einloggen.</p>
</div>
<% end %>